[tool.poetry]
name = "text_affinity"
version = "0.1.0"
description = ""
authors = ["tkhan3 <khantanveera@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.0.1"    
PyYAML = "^5.4.1"
pandas = "^1.3.3"
spacy = "^3.1.3"
wmd = "^1.3.2"
fastapi = "^0.70.0"
gensim = "^4.1.2"
sentence-transformers = "^2.1.0"
tensorflow = "^2.6.0"
tensorflow-hub = "^0.12.0"
uvicorn = "^0.15.0"
poethepoet = "^0.10.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
poethepoet = "^0.10.0"

[tool.poe.tasks]
force-cuda11 = "python -m pip install torch==1.9.1+cu111 torchvision==0.10.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
